services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nyc-streamlit
    expose:
      - "8501"
    volumes:
      - ./cache:/app/cache
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nyc-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - streamlit
    restart: unless-stopped
